### ISSUE TITLE
Splash Screen crashes on Plasma 5+

### ISSUE THREAD

**Issue by emilienbev** [catppuccin/kde#80]
## Issues
The splash screen (`ksplashqml`) crashes when loading either of the Catpuccin splash screens, due to a missing version specification in the `QtQuick` import of `Splash.qml`.

### Stacktrace
```
Application: ksplashqml (ksplashqml), signal: Segmentation fault

[KCrash Handler]
#4  0x00007d35f69110ce in QObject::setProperty(char const*, QVariant const&) () from /lib/x86_64-linux-gnu/libQt5Core.so.5
#5  0x000056deb392cf0d in ?? ()
#6  0x000056deb392b8fa in ?? ()
#7  0x000056deb392c0af in ?? ()
#8  0x000056deb392ad9b in ?? ()
#9  0x00007d35f5e2a1ca in __libc_start_call_main (main=main@entry=0x56deb392acf0, argc=argc@entry=3, argv=argv@entry=0x7ffeff047d38) at ../sysdeps/nptl/libc_start_call_main.h:58
#10 0x00007d35f5e2a28b in __libc_start_main_impl (main=0x56deb392acf0, argc=3, argv=0x7ffeff047d38, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7ffeff047d28) at ../csu/libc-start.c:360
#11 0x000056deb392ae15 in ?? ()
[Inferior 1 (process 27986) detached]
```

## System Details
- Kubuntu 24.04.1 
- Plasma 5.27.11

**Comment by neukus** [comment]
I encountered the same issue on my system:
- Operating System: Kubuntu 24.04
- KDE Plasma Version: 5.27.11
- Qt Version: 5.15.13

This fix worked perfectly on my setup, but I'm not sure if it will help on different versions.

**Comment by neukus** [comment]
The issue has been resolved in version v0.2.5. You can fix it by running:

```bash
git checkout v0.2.5
```

before proceeding with the installation.
According to the release notes, this step is recommended for systems running KDE version 5.27.

**Comment by soleynn** [comment]
henlo @emilienbev closing this out (same thing as your #81).

your diagnosis was right, the qtquick import crashes under qt5. but this branch targets plasma 6 now where the versionless import is correct and the splash works fine. for plasma 5 / 5.27 grab the [v0.2.5 release](https://github.com/catppuccin/kde/releases/tag/v0.2.5), it's built for that. lemme know if u somehow hit it on plasma 6.
